/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <string.h>
#include <stdbool.h>

#define MAX_CLIENTS 1000

bool choosing[MAX_CLIENTS] = {0};
int number_array[MAX_CLIENTS] = {0};

int counter = 0;

int *
get_number_1_svc(void *argp, struct svc_req *rqstp)
{
	static int result;
    
	if (counter >= MAX_CLIENTS)
        counter = 0;

	choosing[counter] = 1;
    int max = 0;
    for (int j = 0; j < MAX_CLIENTS; ++j)
        if (number_array[j] > max)
            max = number_array[j];
    number_array[counter] = ++max;
    choosing[counter] = 0;

    result = number_array[counter];
    printf("Присвоен номер клиента: %d\n", result);
    ++counter;
	return &result;
}

double *
bakery_service_1_svc(struct REQUEST *argp, struct svc_req *rqstp)
{
	static double result;
	int id = argp->number;

	for (int j = 0; j < MAX_CLIENTS; ++j) {
        if (j == id) continue;
        while (choosing[j]);
        while (number_array[j] != 0 && (number_array[j] < number_array[id] || (number_array[j] == number_array[id] && j < id)));
    }
    switch (argp->operation) {
        case '+':
            result = argp->arg1 + argp->arg2;
            break;
        case '-':
            result = argp->arg1 - argp->arg2;
            break;
        case '*':
            result = argp->arg1 * argp->arg2;
            break;
        case '/':
            if(argp->arg2 != 0)
                result = argp->arg1 / argp->arg2;
            else {
                fprintf(stderr, "Ошибка: Деление на ноль от клиента с номером %d.\n", id);
                result = 0;
            }
            break;
        default:
            fprintf(stderr, "Неизвестная операция от клиента с номером %d.\n", id);
            result = 0;
            break;
    }
    printf("Клиент с номером %d выполнил операцию: %.2f %c %.2f = %.2f\n", id, argp->arg1, argp->operation, argp->arg2, result);

	return &result;
}
