/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bakery.h"

bool_t
xdr_OPERATION (XDR *xdrs, OPERATION *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_REQUEST (XDR *xdrs, REQUEST *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->index))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pid))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->number))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->index);
		IXDR_PUT_LONG(buf, objp->pid);
		IXDR_PUT_LONG(buf, objp->number);
		}
		 if (!xdr_float (xdrs, &objp->arg1))
			 return FALSE;
		 if (!xdr_OPERATION (xdrs, &objp->operation))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->arg2))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->res))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->index))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->pid))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->number))
				 return FALSE;

		} else {
		objp->index = IXDR_GET_LONG(buf);
		objp->pid = IXDR_GET_LONG(buf);
		objp->number = IXDR_GET_LONG(buf);
		}
		 if (!xdr_float (xdrs, &objp->arg1))
			 return FALSE;
		 if (!xdr_OPERATION (xdrs, &objp->operation))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->arg2))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->res))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->index))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->number))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_OPERATION (xdrs, &objp->operation))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
