/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <time.h>

char get_operation_char(char op) {
    switch(op) {
        case 'a':
            return '+';
        case 'b':
            return '-';
        case 'c':
            return '*';
        case 'd':
            return '/';
        default:
            return '?';
    }
}

void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	int  *number;
	char *get_number_1_arg;
	double  *result;
	struct REQUEST req;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	while (1) {
		sleep(rand() % 2 + 1);
        memset(&req, 0, sizeof(req));
        number = get_number_1((void *)get_number_1_arg, clnt);
        if (number == (int *) NULL) {
            clnt_perror (clnt, "call failed");
		}
        req.number = *number;
        printf("Новый клиент получил номер %d\n", req.number);
        req.arg1 = ((double)(rand() % 1000)) / 10.0; 
        req.arg2 = ((double)(rand() % 1000)) / 10.0; 
		req.operation = get_operation_char((char)(rand() % 4 + 'a'));
        if(req.operation == 'd' && req.arg2 == 0.0) {
            req.arg2 = ((double)(rand() % 1000)) / 10.0;
            if (req.arg2 == 0.0) req.arg2 = 1.0; 
        }

		sleep(rand() % 1);
        result = bakery_service_1(&req, clnt);
        if (result == (double*) NULL) {
            clnt_perror (clnt, "call failed");
        }

        printf("%.2f %c %.2f = %.2f\n", req.arg1, req.operation, req.arg2, *result);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1 (host);
exit (0);
}
